### ISSUE TITLE
Add simple CI to test the playbook

### ISSUE THREAD

**Issue by fdiblen** [ci-for-research/self-hosted-runners#10]
See
https://misfra.me/2019/10/using-ansible-with-github-actions/
https://github.com/marketplace/actions/run-ansible-playbook

Add Github action workflow to this repo that uses a docker container to test the playbook after every push.

**Comment by HannoSpreeuw** [comment]
Fixing this seems relatively straightforward, except for retrieving the ssh key. 
I mean, the CI workflow yaml file needs instructions to retrieve the ssh key.
And we cannot store that key anywhere safe, because safe means GH Actions cannot retrieve it.
Any suggestions?

**Comment by sverhoeven** [comment]
Ansible roles be tested with https://molecule.readthedocs.io/en/latest/

**Comment by jspaaks** [comment]
Re ssh keys, we could take the same approach as xenon https://github.com/xenon-middleware/xenon-docker-images/tree/master/ssh

**Comment by HannoSpreeuw** [comment]
> See
> https://misfra.me/2019/10/using-ansible-with-github-actions/
> https://github.com/marketplace/actions/run-ansible-playbook
> 
> Add Github action workflow to this repo that uses a docker container to test the playbook after every push.

That first link actually provides a nice solution to the encryption of an ssh key using ansible-vault.
Still requires the storage of the encrypted ssh key, though.

**Comment by HannoSpreeuw** [comment]
> Ansible roles be tested with https://molecule.readthedocs.io/en/latest/

@sverhoeven Perhaps we can talk about this? I don't yet understand what this issue has to do with [ansible roles](https://docs.ansible.com/ansible/latest/user_guide/playbooks_reuse_roles.html).

**Comment by sverhoeven** [comment]
An Ansible role provisions a certain thing using a group of tasks, handlers, variables. The thing in our case is Docker and the GitHub Action runner. We are using other peoples roles to provision these. So these dont need testing by us.

For non-root environments we might make a Ansible roles ourselves which we should test.

**Comment by fdiblen** [comment]
Molecule works with ansible roles. Testing will require us to convert all our playbooks to roles. We have manually tested the playbooks and we can consider automated tests if there is enough interest.
