### ISSUE TITLE
Software installed on self hosted runners

### ISSUE THREAD

**Issue by fdiblen** [ci-for-research/self-hosted-runners#107]
Microsoft has some pre-installed software on their servers. 
https://docs.github.com/en/actions/reference/software-installed-on-github-hosted-runners

When we setup self-hosted runners, CI workflows may fail if the actions need the software listed at the link above. Users should install needed packages before using the workflows(e.g. Python 3.6 for example-python-1)

This information should be added to the guides.

**Comment by fdiblen** [comment]
For Python
See: https://github.com/actions/setup-python#using-setup-python-with-a-self-hosted-runner

**Comment by jspaaks** [comment]
I was under the impression that this type of information would populate directories such as (what used to be called) ``with-cuda``. Specifically for your example, we'd need to add ``with-python``. Perhaps there are reasons not to do it this way?

**Comment by fdiblen** [comment]
This was fixed for Docker guide.
Recipe:
- create the cache folder
```shell
/opt/hostedtoolcache
```
- set environment variable:
```shell
export AGENT_TOOLSDIRECTORY=/opt/hostedtoolcache
```
- adjust the permissions for the user which will start the runner
```shell
sudo chown runner-user:runner-group opt/hostedtoolcache/
```
