### ISSUE TITLE
Lint the Ansible playbook

### ISSUE THREAD

**Issue by fdiblen** [ci-for-research/self-hosted-runners#11]
Refs #10 

See 
https://www.ansible.com/blog/ansible-linting-with-github-actions
https://github.com/marketplace/actions/ansible-lint

Should ideally be a Github workflow.

**Comment by jspaaks** [comment]
@fdiblen what did you mean with "the Ansible playbook" --there are many now.

**Comment by fdiblen** [comment]
@jspaaks Initially we had one Ansible playbook. The issue is about running linter for the playbooks in each guide. We can simply do one of the linting options that @AdamBelloum suggested.

**Comment by AdamBelloum** [comment]
I did some tests about ansible-lint for multiple files

- an easy way is to import multiple playbooks is to have one main.yml and then lint them as described in https://dev.to/andresfmoya/multiple-playbooks-in-ansible-2pdc
- 2nd option is to lint the multiple playbooks as described in https://github.com/marketplace/actions/ansible-lint 
- 3rd option is to use roles but it requires to have a well-defined structure to the repo (I think it is not very convenient)

**Comment by fdiblen** [comment]
I think we can we should replace
```
          targets: "self-hosted-runners/ubuntu-vagrant/playbook.yml"
```

with:

```yaml
with:
  targets: |
    ubuntu-vagrant/runner/playbook.yml
    ubuntu-surf-hpc-cloud/runner/playbook.yml
    ...
```

**Comment by AdamBelloum** [comment]
yes I agree then we will go for 2nd option I have listed https://github.com/ci-for-research/self-hosted-runners/issues/11#issuecomment-651613081
