### ISSUE TITLE
Add instructions for GitHub configuration 

### ISSUE THREAD

**Issue by fdiblen** [ci-for-research/self-hosted-runners#13]
Once CI server is setup, user needs to configure her/his repository to use this server. We need to explain the steps to do that.

**Comment by jspaaks** [comment]
done for ``ubuntu-virtualbox`` https://github.com/NLESC-JCER/linux_actions_runner/pull/54

**Comment by fdiblen** [comment]
done for ubuntu-vagrant and ubuntu-hpc

**Comment by jspaaks** [comment]
Issue can be closed AFAIC
