### ISSUE TITLE
Add Instructions for ubuntu-cartesius/slurm

### ISSUE THREAD

**Issue by fdiblen** [ci-for-research/self-hosted-runners#17]
Write instructions to run CI runner on Cartesius.

Create a playbook for Cartesius that doesn't use docker or root permissions and wait in the queue.
Add to table in the README.

**Comment by jspaaks** [comment]
Follow the template once #85 is merged.

**Comment by jspaaks** [comment]
Changed issue title in anticipation of #85 being merged. 

(How) do we want to run the runner? Install as part of the job every time?
