### ISSUE TITLE
Instructions for Mac

### ISSUE THREAD

**Issue by fdiblen** [ci-for-research/self-hosted-runners#39]
We need the instructions below for Mac.
- [x] remote machine at SURF HPC Cloud 
- [x] local machine via Docker
- [x] local machine via VirtualBox

Most of the instructions for Linux will probably work but some additional steps or changes may be required.

Links to Linux instructions can be found below.
[remote machine at SURF HPC Cloud](https://github.com/NLESC-JCER/linux_actions_runner/blob/master/ubuntu-surf-hpc-cloud/README.md)
[local machine via Docker](https://github.com/NLESC-JCER/linux_actions_runner/blob/master/ubuntu-docker/README.md)
[local machine via VirtualBox](https://github.com/NLESC-JCER/linux_actions_runner/blob/master/ubuntu-virtualbox/README.md)

**Comment by jspaaks** [comment]
I removed label high priority because we have no hardware on which to test this.
