### ISSUE TITLE
ubuntu virtualbox run-through notes

### ISSUE THREAD

**Issue by sverhoeven** [ci-for-research/self-hosted-runners#75]
* `/home/.ssh` in point 8 of https://github.com/ci-for-science/self-hosted-runners/tree/runner-as-a-service/ubuntu-virtualbox#server-side-configuration should be `/home/tester/.ssh`

* Installing Ansible with ppa failed on Ubuntu 20.04 client with

    ```
    E: The repository 'http://ppa.launchpad.net/ansible/ansible/ubuntu focal Release' does not have a 
    Release file.
    N: Updating from such a repository can't be done securely, and is therefore disabled by default.
   ```
    `sudo apt install ansible` installed version from ubuntu archive instead of ansible ppa.

**Comment by jspaaks** [comment]
> sudo apt install ansible installed version from ubuntu archive instead of ansible ppa.

That's what I tried first (on 18.04), but I subsequently experienced problems which I attributed to that being an old version of Ansible (2.5? not sure). I would prefer to install from ubuntu repos, so maybe we should just explicityl state that the instructions are for 20.04 only.

**Comment by jspaaks** [comment]
https://github.com/ci-for-science/self-hosted-runners/pull/68#discussion_r444128500 (Consider using the ``systemd`` Ansible module)
