### ISSUE TITLE
Add instructions for ubuntu-das5/slurm

### ISSUE THREAD

**Issue by fdiblen** [ci-for-research/self-hosted-runners#84]
Write instructions to run CI runner on DAS5.

Create a playbook for DAS5 that doesn't use docker or root permissions and wait in the queue.
Add to table in the README.

**Comment by jspaaks** [comment]
Should we limit this option to one OS, at least initially?

**Comment by jspaaks** [comment]
Changed title in anticipation of #85 being merged. 

(How) do we want to run the runner? Install as part of the job every time?

**Comment by jspaaks** [comment]
DAS has IP whitelisting too

**Comment by fdiblen** [comment]
Possible steps to proceed:
- Start your VPN connection to access DAS5
- Create a socks proxy to get an access to DAS5. See [here](https://www.digitalocean.com/community/tutorials/how-to-route-web-traffic-securely-without-a-vpn-using-a-socks-tunnel) for examples.
- Install GA-runner in users home directory by using Ansible
- Submit a job which will run GA-runner (via Xenon?)
- Github should use the runner in the job

**Comment by fdiblen** [comment]
Or just Singularity ;)
