### ISSUE TITLE
Ansible user in hosts files

### ISSUE THREAD

**Issue by fdiblen** [ci-for-research/self-hosted-runners#90]
Make sure we have the same ansible user in hosts files.

**Comment by jspaaks** [comment]
proposed steps , to be discussed

- ssh as unprivileged user
- then in the playbook use ``become: True`` for tasks that require elevated permissions like installing. Maybe also add ``become_user: root`` to help being explicit about what user you're becoming.
- add ``--ask-become-pass`` to ``ansible-playbook`` command line for playbooks that require root permissions

**Comment by cwmeijer** [comment]
We will work on  "add --ask-become-pass to ansible-playbook command line for playbooks that require root permissions" but not on the other two. We will leave them for when there is time for it.
